# Generated by Django 4.1.3 on 2022-12-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=49)),
                ('branch', models.CharField(max_length=30)),
                ('issue', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('solved', 'solved'), ('un solved', 'un solved')], default='un solved', max_length=90)),
            ],
        ),
    ]
