# Generated by Django 4.1.3 on 2022-12-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('name', models.CharField(max_length=49)),
                ('model', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=20)),
                ('mileage', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='motor',
        ),
    ]
